send_turn_on_command:
  target:
    entity:
      integration: grubstation
  fields:
    broadcast_address:
      required: false
      example: "255.255.255.255"
      selector:
        text:
    broadcast_port:
      required: false
      example: 9
      default: 9
      selector:
        number:
          min: 0
          max: 65535

send_turn_off_command:
  target:
    entity:
      integration: grubstation
