# https://www.home-assistant.io/integrations/default_config/
default_config:

# https://www.home-assistant.io/integrations/homeassistant/
homeassistant:
  name: Grubstation Dev

# https://www.home-assistant.io/integrations/logger/
logger:
  default: info
  logs:
    custom_components.grubstation: debug
